#!/bin/bash

echo -e "Type "go" to start\n"
read go

phase=1

if [ go = go ]; then
	
	while [ $phase = 1 ]
	do	
	
	paplay -p ~/Skripte/Tier
	
		if [ -e phase2 ]; then
			phase=2
		fi	
	done
fi

#if [ $Auswahl = "b)" ]; then
#
#	paplay -p "~/Audio/Samples+Recording/Tier/180803 Purzel 1.wav"
#fi
